import 'package:stripe/src/utils/map_extension.dart';

/// A class that helps generating queries for expanding API responses.
/// [expandableFields] must be implemented.
///
/// Examples of queries that can be generated by [expandQuery] method:
/// ```
/// ["discounts"]
/// ["latest_invoice.payment_intent", "latest_invoice.payment_intent"]
/// ```
///
/// /// Expanding Stripe API responses: https://docs.stripe.com/expand
abstract class ExpandableObject<T> {
  Map<String, ExpandableObject?> get expandableFields;

  Map<String, ExpandableObject> get expand =>
      expandableFields.whereValueNotNull();

  const ExpandableObject();

  List<String>? expandQuery() {
    final query = _generateExpandQuery().toList();

    if (query.isEmpty) return null;

    return query.toList();
  }

  Iterable<String> _generateExpandQuery() sync* {
    for (final fieldEntry in expand.entries) {
      final fieldName = fieldEntry.key;
      final fieldExpandObject = fieldEntry.value;
      yield* _generateExpandQueryForField(fieldName, fieldExpandObject);
    }
  }

  Iterable<String> _generateExpandQueryForField(
    String name,
    ExpandableObject<dynamic> object,
  ) sync* {
    final innerExpandFields = object.expandQuery();

    if (innerExpandFields == null || innerExpandFields.isEmpty) {
      yield name;
    } else {
      for (final field in innerExpandFields) {
        yield [name, field].join('.');
      }
    }
  }
}

/// An implementation of ExpandableObject<T> for objects that don't have any
/// nested expandable fields.
class SimpleExpandableObject<T> extends ExpandableObject<T> {
  @override
  Map<String, ExpandableObject?> get expandableFields => const {};

  const SimpleExpandableObject();
}
